# Generated by Django 2.2.5 on 2019-10-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
