# Generated by Django 2.2.5 on 2019-10-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='AccessRecord',
            old_name='name',
            new_name='t_name',
        ),
    ]
