# Generated by Django 2.2.5 on 2019-10-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20191019_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecorde',
            new_name='AccessRecord',
        ),
    ]
